version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=interview
      - POSTGRES_USER=interview
      - POSTGRES_DB=interview
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10

  data_generator:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy